Missing the exec in the init script.

diff --git a/server/scripts/sfosaka b/server/scripts/sfosaka
--- a/server/scripts/sfosaka
+++ b/server/scripts/sfosaka
@@ -1,23 +1,30 @@
 #! /bin/sh
-#
-# fangalcohol    Startup script for Django server through gunicorn
-#
-# Version:       1.0
-#
+### BEGIN INIT INFO
+# Provides:          skeleton
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Example initscript
+# Description:       This file should be used to construct scripts to be
+#                    placed in /etc/init.d.
+### END INIT INFO
 
-# Constants
+# Author: Foo Bar <foobar@baz.org>
+#
+# Please remove the "Author" lines above and replace them
+# with your own name if you copy and modify this script.
+
+# Do NOT "set -e"
+
 GUNICORN_USER=ubuntu
 HOME_DIR=home
-#GUNICORN_USER=wyan
-#HOME_DIR=Users
-
-. /lib/lsb/init-functions
 
 ROOT_DIR=/$HOME_DIR/$GUNICORN_USER/src/github/SFOsaka/server
 GUNICORN=gunicorn
-APPLICATION_DIR=sfosaka
+NAME=sfosaka
+APPLICATION_DIR=$NAME
 CONF_FILE=sfosaka.gconf
-PID_FILE=sfosaka_gunicorn.pid
 APPLICATION=sfosaka.wsgi:application
 
 GUNICORN_PATH=$ROOT_DIR/bin/$GUNICORN
@@ -25,38 +32,143 @@ APPLICATION_PATH=$ROOT_DIR/$APPLICATION_DIR
 CONFIG_PATH=$ROOT_DIR/$APPLICATION_DIR/$CONF_FILE
 PID_PATH=$ROOT_DIR/$APPLICATION_DIR/$PID_FILE
 
-start () {
-      echo "starting up..."
-      if test -f "$PID_PATH"; then
-         stop
-         # Wait to make sure it's killed so we don't step on ourselves
-         sleep 2
-      fi
-      echo "Saving pid file to $PID_PATH"
-      $GUNICORN_PATH -p $PID_PATH -c $CONFIG_PATH --pythonpath $APPLICATION_PATH $APPLICATION
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="SFOsaka backend"
+DAEMON=$GUNICORN_PATH
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/sfosaka
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+        echo "do_start start-stop-daemon --start --quiet --pidfile $PIDFILE --user $GUNICORN_USER --exec $DAEMON --test"
+        echo "do_start start-stop-daemon --start --quiet --pidfile $PIDFILE --user $GUNICORN_USER --exec $DAEMON -- -c $CONFIG_PATH --pythonpath $APPLICATION_PATH $APPLICATION"
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --user $GUNICORN_USER --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --user $GUNICORN_USER --exec $DAEMON -- \
+		-c $CONFIG_PATH --pythonpath $APPLICATION_PATH $APPLICATION \
+		|| return 2
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
 }
 
-stop () {
-      echo "shutting down"
-      PID=`cat $PID_PATH 2>/dev/null`
-      if test -n "$PID" && kill $PID 2>/dev/null; then
-         echo 'shutdown server'
-      fi
-      rm $PID_PATH
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+	return "$RETVAL"
 }
 
-status () {
-      status_of_proc -p $PID_PATH $GUNICORN_PATH $GUNICORN
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	return 0
 }
 
 case "$1" in
-     start)
-        start
-        ;;
-     stop)
-        stop
-        ;;
-     status)
-        status
-        ;;
+  start)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  stop)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  status)
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	;;
+  #reload|force-reload)
+	#
+	# If do_reload() is not implemented then leave this commented out
+	# and leave 'force-reload' as an alias for 'restart'.
+	#
+	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#do_reload
+	#log_end_msg $?
+	#;;
+  restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+		# Failed to stop
+		log_end_msg 1
+		;;
+	esac
+	;;
+  *)
+	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
+	;;
 esac
+
+:
